[modules]
[modules.preprocessor]
name = "com.scalar.dl.benchmarks.smallbank.SmallBankLoader"
path = "./build/libs/scalardl-benchmarks-all.jar"
[modules.processor]
name = "com.scalar.dl.benchmarks.smallbank.SmallBankBench"
path = "./build/libs/scalardl-benchmarks-all.jar"
[modules.postprocessor]
name = "com.scalar.dl.benchmarks.smallbank.SmallBankReporter"
path = "./build/libs/scalardl-benchmarks-all.jar"

[common]
concurrency = 4
run_for_sec = 60
ramp_for_sec = 10

[stats]
realtime_report_enabled = true

[smallbank_config]
num_accounts = 100000
load_concurrency = 4
load_batch_size = 1

[client_config]
config_file = "/path/to/client.properties"
#ledger_host = "localhost"
#auditor_host = "localhost"
#auditor_enabled = "true"
#cert_holder_id = "foo"
#certificate = "../certs/client.pem"
#private_key = "../certs/client-key.pem"
