[modules]
[modules.preprocessor]
name = "com.scalar.dl.benchmarks.ycsb.YcsbLoader"
path = "./build/libs/scalardl-benchmarks-all.jar"
[modules.processor]
name = "com.scalar.dl.benchmarks.ycsb.YcsbBench"
path = "./build/libs/scalardl-benchmarks-all.jar"
[modules.postprocessor]
name = "com.scalar.dl.benchmarks.ycsb.YcsbReporter"
path = "./build/libs/scalardl-benchmarks-all.jar"

[common]
concurrency = 4
run_for_sec = 60
ramp_for_sec = 10

[stats]
realtime_report_enabled = true

[ycsb_config]
record_count = 100000
payload_size = 100
ops_per_tx = 2
workload = "A" # A, C or F are supported
load_concurrency = 4
load_batch_size = 1

[client_config]
config_file = "../conf/client.properties"
#ledger_host = "localhost"
#auditor_host = "localhost"
#auditor_enabled = "true"
#cert_holder_id = "foo"
#certificate = "../certs/client.pem"
#private_key = "../certs/client-key.pem"
